steps:
- checkout: self

- task: PowerShell@2
  displayName: 'Run builds'
  inputs:
    targetType: filePath
    filePath: './github/run-ci-builds.ps1'
    arguments: |
        -RepositoryFullName $(REPOSITORY_FULL_NAME) `
        -AccessToken $(GITHUB_TOKEN) `
        -WorkflowFileName $(WORKFLOW_FILE_NAME) `
        -WorkflowDispatchRef $(DISPATCH_REF) `
        -ToolVersions "$(ToolVersions)" `
        -PublishReleases $(PUPLISH_RELEASES)