name: 'GitHub Actions humans.txt'
description: 'List out the humans who help feed and tend the robots of GitHub Actions'
inputs:
  format:
    description: 'How to output the people of actions - txt, json, html or ascii'
    default: 'ascii'
  output:
    description: 'Where to output the file - stdout otherwise'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - "${{ inputs.format }}"
  - "${{ inputs.output }}"
