curl "https://api.github.com/orgs/actions/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone

git clone https://github.com/actions/heroku.git
git clone https://github.com/actions/github.git
git clone https://github.com/actions/labeler.git
git clone https://github.com/actions/toolkit.git
git clone https://github.com/actions/runner.git
git clone https://github.com/actions/setup-node.git
git clone https://github.com/actions/virtual-environments.git
git clone https://github.com/actions/setup-go.git
git clone https://github.com/actions/setup-dotnet.git
git clone https://github.com/actions/setup-python.git
git clone https://github.com/actions/upload-artifact.git
git clone https://github.com/actions/download-artifact.git
git clone https://github.com/actions/typescript-action.git
git clone https://github.com/actions/container-action.git
git clone https://github.com/actions/setup-ruby.git
git clone https://github.com/actions/setup-java.git
git clone https://github.com/actions/checkout.git
git clone https://github.com/actions/starter-workflows.git
git clone https://github.com/actions/container-toolkit-action.git
git clone https://github.com/actions/first-interaction.git
git clone https://github.com/actions/hello-world-javascript-action.git
git clone https://github.com/actions/stale.git
git clone https://github.com/actions/hello-world-docker-action.git
git clone https://github.com/actions/example-services.git
git clone https://github.com/actions/setup-elixir.git
git clone https://github.com/actions/github-script.git
git clone https://github.com/actions/javascript-action.git
git clone https://github.com/actions/create-release.git
git clone https://github.com/actions/upload-release-asset.git
git clone https://github.com/actions/setup-haskell.git
git clone https://github.com/actions/.github.git
git clone https://github.com/actions/cache.git
git clone https://github.com/actions/humans.txt.git
git clone https://github.com/actions/http-client.git
git clone https://github.com/actions/virtual-environments-packages.git
git clone https://github.com/actions/delete-package-versions.git
git clone https://github.com/actions/python-versions.git
git clone https://github.com/actions/versions-package-tools.git
git clone https://github.com/actions/node-versions.git
git clone https://github.com/actions/boost-versions.git
git clone https://github.com/actions/go-versions.git
git clone https://github.com/actions/actions-sync.git
